print("Hello, how old are you?")
xString = int(input())
print("In five years you will be " + str(xString+5))
print("Your age times 10 is " + str(xString * 10))
print("Your age divded by 3 is " + str(xString // 3) + " remainder " + str(xString % 3))
